//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ElevatorView : ViewBase
{
    public UnityEngine.UI.Button FirstFloorButton;
    
    public UnityEngine.UI.Button SecondFloorButton;

    public UnityEngine.UI.Button ThirdFloorButton;

    public UnityEngine.UI.Button ForthFloorButton;

    public UnityEngine.UI.Button DownFloorButton;
}
